version: '3.6'

volumes:
  mariadb_data:
    driver: local

# Platform Services
services:

  # HAProxy Load Balancer Proxy
  haproxy:
    image: haproxytech/haproxy-alpine:2.7
    container_name: haproxy
    volumes:
      - ./platform/haproxy:/usr/local/etc/haproxy:ro
    links:
      - tv_nexa_api_service_1
      - tv_nexa_api_service_2
      - tv_nexa_api_service_3
    ports:
      - "9090:9090"
      - "9191:9191"

  # FTP configuration repository
  ftp_repository:
    container_name: ftp_repository
    image: garethflowers/ftp-server
    env_file:
      - .env
    environment:
      - FTP_PASS=${FTP_PASS}
      - FTP_USER=${FTP_USER}
    ports:
      - "20:20"
      - "21:21"
      - "22:22"
      - "40000:40000"
      - "40001:40001"
      - "40002:40002"
      - "40003:40003"
      - "40004:40004"
      - "40005:40005"
      - "40006:40006"
      - "40007:40007"
      - "40008:40008"
      - "40009:40009"
    volumes:
      - ./platform/ftp/data:$FTP_HOME_USER_PATH

  tv_nexa_api_service_1:
    container_name: tv_nexa_api_service_1
    image: ssanchez11/tv_nexa_api_service:0.0.1
    links:
      - ftp_repository

  tv_nexa_api_service_2:
    container_name: tv_nexa_api_service_2
    image: ssanchez11/tv_nexa_api_service:0.0.1
    links:
      - ftp_repository

  tv_nexa_api_service_3:
    container_name: tv_nexa_api_service_3
    image: ssanchez11/tv_nexa_api_service:0.0.1
    links:
      - ftp_repository